import './globals.css'
import {PropsWithChildren} from 'react';

export const metadata = {
  title: 'Test Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: PropsWithChildren) {
  return (
    <html lang="en">
      <body>
        {children}
      </body>
    </html>
  )
}